### ISSUE TITLE
Tweener variables mixed up

### ISSUE THREAD

**Issue by KamiGrave** [ChilliWorks/ChilliSource#3]
Inside the Tweener class (ChilliSource/Core/Tweener.h) the get and set methods for the start and end delays the variable names appear to be mixed up. Call me a traditionalist, but when I can SetStartDelay, I expect it to set m_startDelay, not m_endDelay. The opposite happens in SetEndDelay.

I've fixed it in my fork, so you can either pull from that or fix it yourselves (it's two lines).

**Comment by Chilli-Ian** [comment]
This is now fixed in master.
