### ISSUE TITLE
CSCore::MathUtils::RandomInRange has tiny chance of returning highest number in u32s

### ISSUE THREAD

**Issue by KamiGrave** [ChilliWorks/ChilliSource#4]
Because of the generic way that RandomInRange is done the highest range value is never going to be selected unless FRand() returns 1. I believe this only occurs in integers because of integer rounding.

i.e.

return in_min + (TValueType)(FRand()*(in_max - in_min));

in_min = 2
in_max = 5
FRand() = 0.999999999f

2 + (int)(0.999999999f*(5 - 2))
2 + (int)(0.999999999f*3)
2 + (int)2.999999997
2 + 2
= 4

Unless FRand produces 1.f, you will never get 5.
While the RandomInRange does not specify that each number has equal chance of being selected I would argue that a number having a lower chance than others of being returned makes it less random (Makes it useless for dice rolls). Either it should be fixed so that integers behave as expected or the function comments should specify that highest number in integers is less likely to be returned.

My work around at the moment is to call this function using floats and round the result.

**Comment by Chilli-Ian** [comment]
MathUtils::RandomInRange() has been replaced by Random::Generate() which uses an integer distrubution if an integer type is used which solves this issue.
