### ISSUE TITLE
Getting wrong world transform

### ISSUE THREAD

**Issue by hammeron-art** [ChilliWorks/ChilliSource#9]
```c++
auto& transform = object->GetTransform();

auto previousPos = CSCore::Vector3(transform.GetWorldPosition());

auto worldTransform = CSCore::Matrix4(transform.GetWorldTransform());
auto result = worldTransform * CSCore::Matrix4::CreateTranslation(CSCore::Vector3(3.0f, 0.0, 0.0));
transform.SetWorldTransform(result);

transform.GetWorldTransform();	// need to call to update transform

CS_ASSERT(transform.GetWorldPosition() != previousPos, "Wrong world position");
```
Manually set the world matrix for an entity will return wrong when asking Transform::GetWorld...() methods because it return the local values when there is no parent.

Also manually set the world matrix for an entity with a parent will return wrong local values.

**Comment by Chilli-Ian** [comment]
I've merged your fix into our development branch and will include it in release-v1.4.3 which will be pushed to Github on Thursday (2015-05-21).

Thank you :)
